// Inlines dist/rg-wasm32-wasip1.wasm into lib/_rg.wasm.mjs as a z85 ESM module.
// Run with: `node build.ts`

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { brotliCompressSync, constants as zlibConstants } from "node:zlib";

// z85 alphabet (ZeroMQ RFC 32): 85 printable ASCII chars, none of which
// require escaping inside a JS double-quoted string (no ", \, or backtick).
const Z85 =
  "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{}@%$#";

function z85Encode(bytes: Uint8Array): string {
  const pad = (4 - (bytes.length % 4)) % 4;
  const padded = new Uint8Array(bytes.length + pad);
  padded.set(bytes);
  let out = "";
  for (let i = 0; i < padded.length; i += 4) {
    let n =
      padded[i] * 0x1000000 +
      ((padded[i + 1] << 16) | (padded[i + 2] << 8) | padded[i + 3]);
    n = n >>> 0;
    let s = "";
    for (let j = 0; j < 5; j++) {
      s = Z85[n % 85] + s;
      n = Math.floor(n / 85);
    }
    out += s;
  }
  return out;
}

const root = new URL("./", import.meta.url);
const wasmUrl = new URL("./dist/rg-wasm32-wasip1.wasm", root);
const outUrl = new URL("./lib/_rg.wasm.mjs", root);

const wasm = await readFile(wasmUrl);

const compressed = brotliCompressSync(wasm, {
  params: {
    [zlibConstants.BROTLI_PARAM_QUALITY]: zlibConstants.BROTLI_MAX_QUALITY,
    [zlibConstants.BROTLI_PARAM_MODE]: zlibConstants.BROTLI_MODE_GENERIC,
    [zlibConstants.BROTLI_PARAM_SIZE_HINT]: wasm.byteLength,
  },
});

const encoded = z85Encode(compressed);
const wasmHash = createHash("sha256").update(wasm).digest("hex").slice(0, 16);

const out = /* js */ `// Auto-generated by build.ts — do not edit.
// Source: dist/rg-wasm32-wasip1.wasm (${wasm.byteLength} bytes, brotli → ${compressed.byteLength} bytes)

import { brotliDecompressSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const Z85 = ${JSON.stringify(Z85)};
const compressedByteLength = ${compressed.byteLength};
const cacheFile = join(tmpdir(), "ripgrep-wasm-${wasmHash}.wasm");

// Wrapped in a function so V8 lazy-parses the large string literal and only
// allocates it on first call, rather than at module import time.
const getEncoded = () => ${JSON.stringify(encoded)};

function z85Decode(str, len) {
  const map = new Uint8Array(128);
  for (let i = 0; i < 85; i++) map[Z85.charCodeAt(i)] = i;
  const out = new Uint8Array((str.length / 5) * 4);
  for (let i = 0, j = 0; i < str.length; i += 5, j += 4) {
    let n = 0;
    for (let k = 0; k < 5; k++) n = n * 85 + map[str.charCodeAt(i + k)];
    out[j] = (n >>> 24) & 0xff;
    out[j + 1] = (n >>> 16) & 0xff;
    out[j + 2] = (n >>> 8) & 0xff;
    out[j + 3] = n & 0xff;
  }
  return out.subarray(0, len);
}

function readCache() {
  try {
    return readFileSync(cacheFile);
  } catch {}
}

function writeCache(bytes) {
  try {
    writeFileSync(cacheFile, bytes);
  } catch {}
}

// Returns the decompressed wasm bytes as a Uint8Array. Intended to be fed
// straight into WebAssembly.compile — plain compile is measurably faster than
// compileStreaming for an in-memory source, and simpler (no Response wrapper).
// On first call, decodes z85 + decompresses brotli and caches the result to
// the OS temp dir. Subsequent calls (even across processes) read from cache.
export function getRgWasmBytes() {
  const cached = readCache();
  if (cached) return cached;
  const compressed = z85Decode(getEncoded(), compressedByteLength);
  const bytes = brotliDecompressSync(compressed);
  writeCache(bytes);
  return bytes;
}

export default getRgWasmBytes;
`;

await writeFile(outUrl, out);

const pct = ((encoded.length / wasm.byteLength) * 100).toFixed(1);
console.log(
  `wrote ${fileURLToPath(outUrl)} (wasm ${wasm.byteLength} → brotli ${compressed.byteLength} → z85 ${encoded.length} bytes, ${pct}%)`,
);
