import { brotliDecompressSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// Auto generated by build.ts
const WASM_HASH = "226bbe1107b2cfe2";

const cacheFile = join(tmpdir(), `ripgrep-wasm-${WASM_HASH}.wasm`);

let _wasmModule;

export function getRgWasmModule() {
  if (!_wasmModule) {
    _wasmModule = getRgWasmBytes().then((bytes) => WebAssembly.compile(bytes));
  }
  return _wasmModule;
}

async function getRgWasmBytes() {
  try {
    return readFileSync(cacheFile);
  } catch {}
  const { getCompressedBytes } = await import("./_rg.wasm.mjs");
  const bytes = brotliDecompressSync(getCompressedBytes());
  try {
    writeFileSync(cacheFile, bytes);
  } catch {}
  return bytes;
}

export async function createWasiRuntime({
  args,
  stdout,
  stderr,
  env,
  nodeWasi,
  preopens,
  returnOnExit,
}) {
  const config = { args, stdout, stderr, env, preopens, returnOnExit };
  // node:wasi only accepts numeric fd — fall back to the custom shim for stream-based overrides.
  const hasStreamStdio = (stdout && stdout.fd == null) || (stderr && stderr.fd == null);
  if (!nodeWasi || hasStreamStdio) return createWasiShim(config);

  try {
    return await createNodeWasi(config);
  } catch {
    return createWasiShim(config);
  }
}

let _wasiShim;

async function createWasiShim({ args, stdout, stderr, env, preopens, returnOnExit }) {
  const { createWasi } = await (_wasiShim ??= import("./_wasi.mjs"));
  return createWasi({ args: ["rg", ...args], stdout, stderr, env, preopens, returnOnExit });
}

let _nodeWasi;

async function createNodeWasi({ args, stdout, stderr, env, preopens, returnOnExit }) {
  const prev = process.emitWarning;
  process.emitWarning = () => {};
  try {
    const wasiOptions = {
      version: "preview1",
      args: ["rg", ...args],
      env,
      preopens,
      returnOnExit,
    };
    if (stdout?.fd != null) wasiOptions.stdout = stdout.fd;
    if (stderr?.fd != null) wasiOptions.stderr = stderr.fd;
    const { WASI } = await (_nodeWasi ??= import("node:wasi"));
    var wasi = new WASI(wasiOptions);
  } finally {
    process.emitWarning = prev;
  }
  return {
    imports: wasi.getImportObject(),
    start: (instance) => wasi.start(instance) ?? 0,
  };
}
