import { brotliDecompressSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// Auto generated by build.ts
const WASM_HASH = "4a7dc2d696452852";

const cacheFile = join(tmpdir(), `ripgrep-wasm-${WASM_HASH}.wasm`);

let _wasmModule;

export function getRgWasmModule() {
  if (!_wasmModule) {
    _wasmModule = getRgWasmBytes().then((bytes) => WebAssembly.compile(bytes));
  }
  return _wasmModule;
}

async function getRgWasmBytes() {
  try {
    return readFileSync(cacheFile);
  } catch {}
  const { getCompressedBytes } = await import("./_rg.wasm.mjs");
  const bytes = brotliDecompressSync(getCompressedBytes());
  writeFileSync(cacheFile, bytes);
  return bytes;
}

export async function createWasiRuntime({ args, env, nodeWasi, preopens, returnOnExit }) {
  const config = { args, env, preopens, returnOnExit };
  if (!nodeWasi) return createWasiShim(config);

  try {
    return await createNodeWasi(config);
  } catch {
    return createWasiShim(config);
  }
}

let _wasiShim;

async function createWasiShim({ args, env, preopens, returnOnExit }) {
  const { createWasi } = await (_wasiShim ??= import("./_wasi.mjs"));
  return createWasi({ args: ["rg", ...args], env, preopens, returnOnExit });
}

let _nodeWasi;

async function createNodeWasi({ args, env, preopens, returnOnExit }) {
  const prev = process.emitWarning;
  process.emitWarning = () => {};
  try {
    const { WASI } = await (_nodeWasi ??= import("node:wasi"));
    var wasi = new WASI({
      version: "preview1",
      args: ["rg", ...args],
      env,
      preopens,
      returnOnExit,
    });
  } finally {
    process.emitWarning = prev;
  }
  return {
    imports: wasi.getImportObject(),
    start: (instance) => wasi.start(instance) ?? 0,
  };
}
